apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cz2fium84-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-6a537f80a1.p0a3.p3.openshiftapps.com/rhtap/rhtap-qe:fc8df44223477f573de7382c036ff4b501946bea@sha256:f8cb97a4cf0be48f9438dc67062b83a03dfcccba423baf173f4e957dd39cf1ae
          name: container-image
